const mongoose = require('mongoose');

const payrollSchema = new mongoose.Schema({
  // Basic Information
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  name: {
    type: String,
    required: true
  },
  
  periodStart: {
    type: Date,
    required: true
  },
  
  periodEnd: {
    type: Date,
    required: true
  },
  
  // Attendance Details
  presentDays: {
    type: Number,
    default: 0
  },
  
  absentDays: {
    type: Number,
    default: 0
  },
  
  lateDays: {
    type: Number,
    default: 0
  },
  
  leaveDays: {
    type: Number,
    default: 0
  },
  
  workingDays: {
    type: Number,
    default: 0
  },
  
  // Salary Calculation
  basicPay: {
    type: Number,
    required: true,
    min: 0
  },
  
  overtimeDays: {
    type: Number,
    default: 0
  },
  
  overtimeAmount: {
    type: Number,
    default: 0
  },
  
  leaveDeduction: {
    type: Number,
    default: 0
  },
  
  lateDeduction: {
    type: Number,
    default: 0
  },
  
  bonusAmount: {
    type: Number,
    default: 0
  },
  
  totalDeductions: {
    type: Number,
    default: 0
  },
  
  totalAdditions: {
    type: Number,
    default: 0
  },
  
  netPayable: {
    type: Number,
    required: true,
    min: 0
  },
  
  // Status
  status: {
    type: String,
    enum: ['Pending', 'Paid', 'Rejected', 'Processing'],
    default: 'Pending'
  },
  
  employeeApproved: {
    type: Boolean,
    default: false
  },
  
  employeeApprovedAt: Date,
  
  paymentDate: Date,
  
  rejectionReason: String,
  
  // Salary Rule Reference
  salaryRule: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SalaryRule'
  },
  
  salaryRuleDetails: {
    type: mongoose.Schema.Types.Mixed
  },
  
  // Auto Generation
  autoGenerated: {
    type: Boolean,
    default: false
  },
  
  generatedDate: Date,
  
  calculatedDate: {
    type: Date,
    default: Date.now
  },
  
  notes: String,
  
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  createdAt: {
    type: Date,
    default: Date.now
  },
  
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

// Update timestamp
payrollSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

// Indexes
payrollSchema.index({ employee: 1, periodStart: -1 });
payrollSchema.index({ status: 1 });
payrollSchema.index({ autoGenerated: 1 });
payrollSchema.index({ periodStart: 1, periodEnd: 1 });

const Payroll = mongoose.model('Payroll', payrollSchema);
module.exports = Payroll;