const mongoose = require('mongoose');

const payrollSchema = new mongoose.Schema({
  // Employee Information
  employee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  employeeName: {
    type: String, 
  },
  employeeId: {
    type: String, 
  }, 
  // Pay Period
  periodStart: {
    type: Date,
    required: true
  },
  periodEnd: {
    type: Date,
    required: true
  },
  
  // Payroll Status
  status: {
    type: String,
    enum: ['Pending', 'Paid', 'Approved', 'Rejected', 'Draft', 'pending_approval', 'Processing'],
    default: 'Pending'
  },
  
  // Basic Information
  notes: {
    type: String,
    default: ''
  },
  month: {
    type: Number, 
  },
  year: {
    type: Number, 
  },
  
  // Salary Details
  salaryDetails: {
    monthlySalary: {
      type: Number,
      required: true,
      default: 0
    },
    dailyRate: {
      type: Number,
      required: true,
      default: 0
    },
    hourlyRate: {
      type: Number,
      required: true,
      default: 0
    },
    basicSalary: {
      type: Number,
      default: 0
    },
    houseRent: {
      type: Number,
      default: 0
    },
    medicalAllowance: {
      type: Number,
      default: 0
    },
    conveyance: {
      type: Number,
      default: 0
    }
  },
  
  // Attendance Summary
  attendance: {
    presentDays: {
      type: Number,
      default: 0
    },
    totalWorkingDays: {
      type: Number,
      default: 26
    },
    attendancePercentage: {
      type: Number,
      default: 0
    },
    lateMinutes: {
      type: Number,
      default: 0
    },
    absentDays: {
      type: Number,
      default: 0
    },
    halfDays: {
      type: Number,
      default: 0
    },
    leaveDays: {
      type: Number,
      default: 0
    },
    holidays: {
      type: Number,
      default: 0
    },
    weeklyOffs: {
      type: Number,
      default: 0
    }
  },
  
  // Earnings Breakdown
  earnings: {
    basicPay: {
      type: Number,
      default: 0
    },
    overtime: {
      type: Number,
      default: 0
    },
    overtimeHours: {
      type: Number,
      default: 0
    },
    bonus: {
      type: Number,
      default: 0
    },
    allowance: {
      type: Number,
      default: 0
    },
    houseRent: {
      type: Number,
      default: 0
    },
    medical: {
      type: Number,
      default: 0
    },
    conveyance: {
      type: Number,
      default: 0
    },
    incentives: {
      type: Number,
      default: 0
    },
    otherAllowances: {
      type: Number,
      default: 0
    },
    total: {
      type: Number,
      default: 0
    }
  },
  
  // Deductions Breakdown
  deductions: {
    lateDeduction: {
      type: Number,
      default: 0
    },
    absentDeduction: {
      type: Number,
      default: 0
    },
    leaveDeduction: {
      type: Number,
      default: 0
    },
    halfDayDeduction: {
      type: Number,
      default: 0
    },
    taxDeduction: {
      type: Number,
      default: 0
    },
    providentFund: {
      type: Number,
      default: 0
    },
    advanceSalary: {
      type: Number,
      default: 0
    },
    loanDeduction: {
      type: Number,
      default: 0
    },
    otherDeductions: {
      type: Number,
      default: 0
    },
    total: {
      type: Number,
      default: 0
    },
    breakdown: {
      autoCalculated: {
        type: Number,
        default: 0
      },
      manual: {
        type: Number,
        default: 0
      }
    }
  },
  
  // Summary
  summary: {
    grossEarnings: {
      type: Number,
      default: 0
    },
    totalDeductions: {
      type: Number,
      default: 0
    },
    netPayable: {
      type: Number,
      required: true,
      default: 0
    },
    inWords: {
      type: String,
      default: ''
    },
    payableDays: {
      type: Number,
      default: 0
    }
  },
  
  // Payment Information
  payment: {
    paymentDate: {
      type: Date
    },
    paymentMethod: {
      type: String,
      enum: ['Bank Transfer', 'Cash', 'Cheque', 'Online Payment', 'Not Paid']
    },
    transactionId: {
      type: String
    },
    bankAccount: {
      type: String
    },
    paidBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }
  },
  
  // Metadata
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  createdRole: {
    type: String,
    enum: ['admin', 'employee', 'hr', 'manager']
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  hasLateLeaveCalculations: {
    type: Boolean,
    default: false
  },
  autoDeductionsApplied: {
    type: Boolean,
    default: false
  },
  
  // For auto salary requests
  salaryRequestId: {
    type: String
  },
  generatedFromRequest: {
    type: Boolean,
    default: false
  },
  
  // For bulk generation
  batchId: {
    type: String
  },
  isBulkGenerated: {
    type: Boolean,
    default: false
  },
  
  // Approvals
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  approvedDate: {
    type: Date
  },
  
  // Audit trail
  lastUpdatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  // Soft delete
  isDeleted: {
    type: Boolean,
    default: false
  },
  deletedAt: {
    type: Date
  },
  deletedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
  
}, { 
  timestamps: true 
});

// Indexes for better performance
payrollSchema.index({ employee: 1, month: 1, year: 1 }, { unique: true });
payrollSchema.index({ status: 1 });
payrollSchema.index({ month: 1, year: 1 });
payrollSchema.index({ periodStart: 1, periodEnd: 1 });
payrollSchema.index({ createdBy: 1 });
payrollSchema.index({ 'payment.paymentDate': 1 });

// Pre-save middleware to calculate values
payrollSchema.pre('save', function(next) {
  // Calculate month and year from periodStart
  if (this.periodStart && !this.month) {
    this.month = this.periodStart.getMonth() + 1;
  }
  if (this.periodStart && !this.year) {
    this.year = this.periodStart.getFullYear();
  }
  
  // Calculate attendance percentage
  if (this.attendance && this.attendance.presentDays && this.attendance.totalWorkingDays) {
    this.attendance.attendancePercentage = Math.round(
      (this.attendance.presentDays / this.attendance.totalWorkingDays) * 100
    );
  }
  
  // Calculate earnings total
  if (this.earnings) {
    const earnings = this.earnings;
    earnings.total = 
      (earnings.basicPay || 0) +
      (earnings.overtime || 0) +
      (earnings.bonus || 0) +
      (earnings.allowance || 0) +
      (earnings.houseRent || 0) +
      (earnings.medical || 0) +
      (earnings.conveyance || 0) +
      (earnings.incentives || 0) +
      (earnings.otherAllowances || 0);
  }
  
  // Calculate deductions total
  if (this.deductions) {
    const deductions = this.deductions;
    deductions.total = 
      (deductions.lateDeduction || 0) +
      (deductions.absentDeduction || 0) +
      (deductions.leaveDeduction || 0) +
      (deductions.halfDayDeduction || 0) +
      (deductions.taxDeduction || 0) +
      (deductions.providentFund || 0) +
      (deductions.advanceSalary || 0) +
      (deductions.loanDeduction || 0) +
      (deductions.otherDeductions || 0);
  }
  
  // Calculate summary
  if (this.earnings && this.deductions) {
    this.summary.grossEarnings = this.earnings.total || 0;
    this.summary.totalDeductions = this.deductions.total || 0;
    this.summary.netPayable = 
      (this.earnings.total || 0) - (this.deductions.total || 0);
    this.summary.payableDays = this.attendance?.presentDays || 0;
  }
  
  next();
});

// Method to get payroll in JSON format
payrollSchema.methods.toJSON = function() {
  const obj = this.toObject();
  
  // Remove sensitive data if needed
  delete obj.__v;
  
  // Format dates
  if (obj.periodStart) {
    obj.periodStartFormatted = obj.periodStart.toISOString().split('T')[0];
  }
  if (obj.periodEnd) {
    obj.periodEndFormatted = obj.periodEnd.toISOString().split('T')[0];
  }
  if (obj.payment?.paymentDate) {
    obj.payment.paymentDateFormatted = obj.payment.paymentDate.toISOString().split('T')[0];
  }
  
  return obj;
};

// Static method to find payroll by employee and period
payrollSchema.statics.findByEmployeeAndPeriod = async function(employeeId, periodStart, periodEnd) {
  return this.findOne({
    employee: employeeId,
    periodStart: new Date(periodStart),
    periodEnd: new Date(periodEnd)
  });
};

// Static method to calculate payroll statistics
payrollSchema.statics.getPayrollStats = async function(month, year) {
  const startDate = new Date(year, month - 1, 1);
  const endDate = new Date(year, month, 0);
  
  const stats = await this.aggregate([
    {
      $match: {
        periodStart: { $gte: startDate },
        periodEnd: { $lte: endDate },
        isDeleted: false
      }
    },
    {
      $group: {
        _id: null,
        totalPayrolls: { $sum: 1 },
        totalNetPayable: { $sum: '$summary.netPayable' },
        totalEmployees: { $addToSet: '$employee' },
        totalPaid: {
          $sum: {
            $cond: [{ $eq: ['$status', 'Paid'] }, 1, 0]
          }
        },
        totalPending: {
          $sum: {
            $cond: [{ $eq: ['$status', 'Pending'] }, 1, 0]
          }
        },
        totalApproved: {
          $sum: {
            $cond: [{ $eq: ['$status', 'Approved'] }, 1, 0]
          }
        }
      }
    },
    {
      $project: {
        _id: 0,
        totalPayrolls: 1,
        totalNetPayable: 1,
        totalEmployees: { $size: '$totalEmployees' },
        totalPaid: 1,
        totalPending: 1,
        totalApproved: 1
      }
    }
  ]);
  
  return stats[0] || {
    totalPayrolls: 0,
    totalNetPayable: 0,
    totalEmployees: 0,
    totalPaid: 0,
    totalPending: 0,
    totalApproved: 0
  };
};

const Payroll = mongoose.model('Payroll', payrollSchema);
module.exports = Payroll;